version: '3.8'

services:
  app:
    image: omurturgut/assignment:latest
    container_name: assignment
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/DriverDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=5869
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres/.
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=5869
      - POSTGRES_DB=DriverDB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: